# Generated by Django 3.1.3 on 2020-12-12 00:01

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201211_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=recipe.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
