# Generated by Django 3.1.1 on 2020-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Rating', models.CharField(max_length=255)),
                ('Ease_of_Prep', models.CharField(max_length=255)),
                ('Notes', models.CharField(max_length=255)),
                ('Type', models.IntegerField()),
                ('Prep_Time', models.IntegerField()),
                ('Photo', models.CharField(max_length=255)),
                ('Cookbook', models.CharField(max_length=255)),
                ('Page', models.CharField(max_length=255)),
                ('Ingredients', models.CharField(max_length=255)),
                ('Slowcooker', models.CharField(max_length=255)),
                ('Link', models.CharField(max_length=255)),
                ('Last_Made', models.CharField(max_length=255)),
                ('Make_It_Next', models.CharField(max_length=255)),
                ('RecipeID', models.IntegerField()),
            ],
        ),
    ]
